1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Print the numpy version and the configuration 

In [7]:
print("NumPy Version : ", np.__version__)
print(np.show_config())

NumPy Version :  1.24.2
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macro

3. Create a null vector of size 10

In [61]:
x = np.zeros((10), dtype=int)
print(x)

[0 0 0 0 0 0 0 0 0 0]


4. How to find the memory size of any array 

In [328]:
Z = np.zeros((10, 10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


5. How to get the documentation of the numpy add function from the command line?

In [ ]:
python3 -c "import numpy; numpy.info(numpy.add)"

6. Create a null vector of size 10 but the fifth value which is 1

In [58]:
x = np.zeros((10), dtype=int)
x[4] = 1
print(x)

[0 0 0 0 1 0 0 0 0 0]


7. Create a vector with values ranging from 10 to 49

In [29]:
x = np.arange(10, 50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Reverse a vector (first element becomes last)

In [30]:
x = np.arange(5)
x = x[::-1]
print(x)

[4 3 2 1 0]


9. Create a 3x3 matrix with values ranging from 0 to 8

In [34]:
x = np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [60]:
x = np.nonzero([1,2,0,0,4,0])
print(x)

(array([0, 1, 4]),)


11. Create a 3x3 identity matrix

In [57]:
x = np.eye((3), dtype=int)
print(x)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


12. Create a 3x3x3 array with random values

In [38]:
x = np.random.random((3,3,3))
print(x)

[[[0.34688038 0.32649631 0.64272649]
  [0.71172949 0.78708116 0.59767217]
  [0.67984192 0.38032379 0.98948505]]

 [[0.00814946 0.3171235  0.32840445]
  [0.46728671 0.55126178 0.03597316]
  [0.98735293 0.0709888  0.53690236]]

 [[0.27738032 0.47018746 0.92578661]
  [0.04462677 0.45560097 0.19056061]
  [0.57913911 0.40106568 0.96641163]]]


13. Create a 10x10 array with random values and find the minimum and maximum values

In [41]:
x = np.random.random((10, 10))
xmin, xmax = x.min(), x.max()
print(xmin, xmax)

0.004024807128157004 0.9745836979375939


14. Create a random vector of size 30 and find the mean value

In [43]:
x = np.random.random(30)
xmean = x.mean()
print(xmean)

0.4757517193827672


15. Create a 2d array with 1 on the border and 0 inside

In [56]:
x = np.ones((4, 4), dtype=int)
x[1:-1,1:-1] = 0
print(x)

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


16. How to add a border (filled with 0's) around an existing array?

In [329]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


17. What is the result of the following expression?

In [53]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [55]:
x = np.diag(np.arange(1, 5), k = -1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [68]:
x = np.zeros((8, 8), dtype=int)
x[1::2, ::2] = 1
x[::2, 1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [71]:
x = np.unravel_index(100, (6, 7, 8))
print(x)

(1, 5, 4)


21. Create a checkerboard 8x8 matrix using the tile function

In [74]:
x = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


22. Normalize a 5x5 random matrix

In [83]:
x = np.random.random((5, 5))
xmax, xmin = x.max(), x.min()
x = (x - xmin) / (xmax - xmin)
print(x)

[[0.74348346 0.         0.41568438 0.15190589 0.18659346]
 [0.65683695 0.74213995 0.57347558 0.22994963 0.28833616]
 [0.03220512 0.22318189 1.         0.78698535 0.13991126]
 [0.66694646 0.12061953 0.06507818 0.76251291 0.88918158]
 [0.91193733 0.43173002 0.99450552 0.1597141  0.72625163]]


23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [86]:
x = np.dtype([("r", np.ubyte, 1),
                ("b", np.ubyte, 1),
                ("g", np.ubyte, 1),
                ("a", np.ubyte, 1)])

/var/folders/tv/7k93pwvn05v4jhsnbpfm9ps80000gn/T/ipykernel_4283/128891023.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  x = np.dtype([("r", np.ubyte, 1),


24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [200]:
x = np.dot(np.ones((5, 3), dtype=int), np.ones((3, 2), dtype=int))
print(x)

[[3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]]


25. Given a 1D array, negate all elements which are between 3 and 8, in place. 

In [91]:
x = np.arange(10)
x[(x > 3) & (x <= 8)] *= -1
print(x)

[ 0  1  2  3 -4 -5 -6 -7 -8  9]


26. What is the output of the following script?

In [92]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


27. Consider an integer vector Z, which of these expressions are legal? 

In [ ]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1 - legal
Z<Z>Z

28. What are the result of the following expressions?

In [3]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[0.]


/var/folders/tv/7k93pwvn05v4jhsnbpfm9ps80000gn/T/ipykernel_4621/3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/var/folders/tv/7k93pwvn05v4jhsnbpfm9ps80000gn/T/ipykernel_4621/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/var/folders/tv/7k93pwvn05v4jhsnbpfm9ps80000gn/T/ipykernel_4621/3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


29. How to round away from zero a float array ?

In [17]:
Z = np.random.uniform(-5, 5, 5)
print(np.copysign(np.ceil(np.abs(Z)), Z))


[-4.  4. -2.  5. -1.]


30. How to find common values between two arrays?

In [21]:
x = np.random.randint(0, 10, 10)
y = np.random.randint(0, 10, 10)
z = np.intersect1d(x, y)
print(z)

[0 3 4 6 7]


31. How to ignore all numpy warnings (not recommended)?

In [26]:
x = np.seterr(all="ignore")
y = np.ones(1) / 0

32. Is the following expressions true?

In [27]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

33. How to get the dates of yesterday, today and tomorrow?

In [29]:
y = np.datetime64('today') - np.timedelta64(1)
t = np.datetime64('today')
tt = np.datetime64('today') + np.timedelta64(1)
print(y)
print(t)
print(tt)

2023-03-25
2023-03-26
2023-03-27


34. How to get all the dates corresponding to the month of July 2016?

In [30]:
x = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [202]:
a = np.ones(3) * 1
b = np.ones(3) * 2
print(a, b)
print(np.add(a, b, out=b))
print(np.divide(a, 2, out=a))
print(np.negative(a, out=a))
print(np.multiply(a, b, out=a))

[1. 1. 1.] [2. 2. 2.]
[3. 3. 3.]
[0.5 0.5 0.5]
[-0.5 -0.5 -0.5]
[-1.5 -1.5 -1.5]


36. Extract the integer part of a random array of positive numbers using 4 different methods

In [52]:
x = np.random.randint(0, 10, 10)

print(x // 1)
print(np.floor(x))
print(np.trunc(x))
print(x.astype(int))

[5 3 6 1 7 1 0 3 7 3]
[5. 3. 6. 1. 7. 1. 0. 3. 7. 3.]
[5. 3. 6. 1. 7. 1. 0. 3. 7. 3.]
[5 3 6 1 7 1 0 3 7 3]


37. Create a 5x5 matrix with row values ranging from 0 to 4

In [54]:
x = np.zeros((5, 5), dtype=int)
x += np.arange(5)
print(x)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


38. Consider a generator function that generates 10 integers and use it to build an array

In [59]:
def generate():
    for x in range(10):
        yield x
y = np.fromiter(generate(), dtype=int, count=-1)
print(y)

[0 1 2 3 4 5 6 7 8 9]


39. Create a vector of size 10 with values ranging from 0 to 1, both excluded 

In [60]:
x = np.linspace(0, 1, 11, endpoint=False)[1:]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


40. Create a random vector of size 10 and sort it

In [62]:
x = np.random.random((5))
x.sort()
print(x)

[0.05532529 0.18841542 0.19237827 0.52129273 0.87506206]


41. How to sum a small array faster than np.sum? 

In [63]:
x = np.arange(10)
print(np.add.reduce(x))

45


42. Consider two random array A and B, check if they are equal

In [76]:
a = np.random.randint(0, 2, 5)
b = np.random.randint(0, 2, 5)

x = np.allclose(a, b)
print(x)

True


43. Make an array immutable (read-only)

In [79]:
x = np.zeros(5)
x.flags.writeable = False
print(x)
x[0] = 1
print(x)

[0. 0. 0. 0. 0.]


ValueError: assignment destination is read-only

44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [81]:
x = np.random.random((10, 2))
a, b = x[:, 0], x[:, 1]
q = np.sqrt(a**2 + b**2)
p = np.arctan2(b, a)
print(q)
print(p)

[0.82158813 0.62462117 0.90041287 0.99083305 1.17087403 0.84155138
 0.51823166 0.78604284 0.81678917 0.21068046]
[3.86671800e-01 1.22478157e+00 1.56248714e+00 3.24834369e-01
 7.19226093e-01 9.11228687e-04 2.19562361e-01 1.18507880e+00
 1.09907661e+00 9.24972890e-01]


45. Create random vector of size 10 and replace the maximum value by 0

In [82]:
x = np.random.random(10)
x[x.argmax()] = 0
print(x)

[0.82127714 0.78397186 0.95957974 0.07943523 0.30558096 0.31682115
 0.89032152 0.38712555 0.38074577 0.        ]


46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area

In [83]:
a = np.zeros((5, 5), [('x', float), ('y', float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0, 1, 5),
                             np.linspace(0, 1, 5))
print(a)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [88]:
x = np.arange(3)
z = x + 0.5
y = 1.0 / np.subtract.outer(x, z)
print(y)

[[-2.         -0.66666667 -0.4       ]
 [ 2.         -2.         -0.66666667]
 [ 0.66666667  2.         -2.        ]]


48. Print the minimum and maximum representable value for each numpy scalar type

In [89]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


49. How to print all the values of an array?

In [93]:
np.set_printoptions(threshold=float("inf"))
x = np.zeros((16, 16), dtype=int)
print(x)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


50. How to find the closest value (to a given scalar) in a vector?

In [99]:
x = np.arange(100)
y = np.random.randint(0, 100)
i = (np.abs(x - y)).argmin()
print(x[i])

43


51. Create a structured array representing a position (x,y) and a color (r,g,b)

In [105]:
x = np.zeros(10, [('position', [('x', int, 1), ('y', int, 1)]),
                  ('color', [('r', int, 1), ('g', int, 1), ('b', int, 1)])])
print(x)

[((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0))
 ((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0))
 ((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0))
 ((0, 0), (0, 0, 0))]


/var/folders/tv/7k93pwvn05v4jhsnbpfm9ps80000gn/T/ipykernel_4621/3208493536.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  x = np.zeros(10, [('position', [('x', int, 1), ('y', int, 1)]),


52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances

In [108]:
x = np.random.random((100, 2))
y, q = np.atleast_2d(x[:, 0], x[:, 1])
check = np.sqrt((y - y.T)**2 + (q - q.T)**2)
print(check)

[[0.         0.06762477 0.70019281 0.63207381 0.33718733 0.8640631
  0.76247494 0.18713939 0.96297963 0.42462021 0.67588704 0.42627663
  0.87703517 0.62155026 0.50617803 0.47952445 0.5201375  0.32228317
  0.566758   0.34659058 0.76880255 0.79211336 0.75507865 0.46351076
  0.3230513  0.62284471 0.28457764 0.7395737  0.83122146 0.27879751
  0.45201786 0.18401313 0.10385559 0.75593502 0.32603212 0.54950283
  0.35899376 0.80912484 0.55315941 0.14212538 0.64116269 0.41053528
  0.46321146 0.36318506 0.11717672 0.28576162 0.54249766 0.36793544
  0.14691741 0.82622138 0.50404406 0.81877731 0.43700169 0.24768413
  0.16510254 0.23890587 0.33921924 0.39706209 0.3289569  0.64070455
  0.0802778  0.1173952  0.70851578 0.68859363 0.52996708 0.8560571
  0.60653034 0.5007733  0.62028443 0.21787092 0.24679304 0.12527584
  0.74186454 0.11613404 0.92264281 0.29851583 0.17780134 0.87767329
  0.60273292 0.4409252  0.46701472 0.63292389 0.83045092 0.28622588
  0.24571302 0.31991011 0.49162563 0.22132207 0.32

53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [111]:
x = (np.random.rand(10) * 100).astype(np.float32)
k = x.view(np.int32)
k[:] = x
print(k)

[88 75 56 52 69 62 36 80 82 17]


54. How to read the following file?

In [ ]:
x = np.genfromtxt(file, delimiter=",", dtype=int)

55. What is the equivalent of enumerate for numpy arrays?

In [116]:
x = np.arange(9).reshape(3, 3)
for i in np.ndindex(x.shape):
    print(i, x[i])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


56. Generate a generic 2D Gaussian-like array

In [121]:
x, y = np.meshgrid(np.linspace(-1, 1, 5), np.linspace(-1, 1, 5))
z = np.sqrt(x * x + y * y)
Gauss = np.exp(-(z**2))
print(Gauss)

[[0.13533528 0.2865048  0.36787944 0.2865048  0.13533528]
 [0.2865048  0.60653066 0.77880078 0.60653066 0.2865048 ]
 [0.36787944 0.77880078 1.         0.77880078 0.36787944]
 [0.2865048  0.60653066 0.77880078 0.60653066 0.2865048 ]
 [0.13533528 0.2865048  0.36787944 0.2865048  0.13533528]]


57. How to randomly place p elements in a 2D array?

In [122]:
n = 5
p = 10
x = np.zeros((n, n), dtype=int)
np.put(x, np.random.choice(range(n * n), p, replace=False), 1)
print(x)

[[0 0 1 0 1]
 [0 0 0 0 1]
 [0 1 1 0 0]
 [1 0 1 0 1]
 [0 1 1 0 0]]


58. Subtract the mean of each row of a matrix

In [124]:
x = np.random.rand(5, 5)
check = x - x.mean(axis=1).reshape(-1, 1)
print(check)

[[ 0.02589241  0.07396178 -0.05500008  0.06336037 -0.10821448]
 [-0.26841028  0.25503911 -0.38671547  0.23404058  0.16604605]
 [-0.16115673  0.01631293  0.09121482 -0.32862422  0.3822532 ]
 [ 0.2005037   0.30022713 -0.40463533 -0.28399594  0.18790045]
 [ 0.09410514  0.3232957   0.01192879 -0.05644173 -0.37288789]]


59. How to sort an array by the nth column?

In [128]:
x = np.random.randint(0, 10, (3, 3))
print(x)
print(x[x[:, 0].argsort()])

[[6 5 8]
 [8 4 4]
 [2 0 6]]
[[2 0 6]
 [6 5 8]
 [8 4 4]]


60. How to tell if a given 2D array has null columns?

In [135]:
x = np.random.randint(0, 3, (3, 10))
print((~x.any(axis=0)).any())

True


61. Find the nearest value from a given value in an array

In [137]:
x = np.random.uniform(0, 1, 10)
y = x.flat[np.abs(x - 0.5).argmin()]
print(y)

0.46944010560006566


62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? 

In [140]:
x = np.arange(3).reshape(3, 1)
y = np.arange(3).reshape(1, 3)
i = np.nditer([x, y, None])
for a, b, c in i:
    c[...] = a + b
print(i.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


63. Create an array class that has a name attribute

In [143]:
class NArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        x = np.asarray(array).view(cls)
        x.name = name
        return x
    def __final__(m, x):
        if x is None:
            return
        m.info = getattr(x, 'name', "no name")

check = NArray(np.arange(5), "range_5")
print(check.name)

range_5


64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [146]:
x = np.ones((10), dtype=int)
a = np.random.randint(0, 10, 10)
np.add.at(x, a, 1)
print(a)
print(x)

[7 7 0 6 8 5 7 8 1 2]
[2 2 2 1 1 2 2 4 3 1]


65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

In [204]:
x = [1, 2, 3, 4, 5, 6]
f = [1, 3, 9, 3, 4, 1]
check = np.bincount(f, x)
print(check)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

In [158]:
w, h = 16, 16
x = np.random.randint(0, 2, (h, w, 3)).astype(np.ubyte)
print(np.unique(x))

[0 1]


67. Considering a four dimensions array, how to get sum over the last two axis at once?

In [161]:
x = np.random.randint(0, 10, (3, 4, 3, 4))
sum = x.sum(axis=(-2, -1))
print(sum)

[[55 46 55 65]
 [49 53 60 52]
 [55 60 65 56]]


68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices?

In [173]:
d = np.random.randint(0, 5, 100)
s = np.random.randint(0, 10, 100)
sum = np.bincount(s, weights=d)
count = np.bincount(s)
mean = sum / count
print(mean)

[1.73333333 1.36363636 1.         0.75       1.47058824 1.75
 3.         2.16666667 1.63636364 1.9       ]


69. How to get the diagonal of a dot product?

In [174]:
x = np.random.uniform(0, 1, (5, 5))
y = np.random.uniform(0, 1, (5, 5))
check = np.diag(np.dot(x, y))
print(check)

[0.92804148 0.97869356 1.62482717 1.15529695 0.91538121]


70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [176]:
x = np.array([1, 2, 3, 4, 5])
a = 3
y = np.zeros((len(x) + (len(x) - 1) * a), dtype=int)
y[::a + 1] = x
print(y)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

In [177]:
x = np.ones((5, 5, 3), dtype=int)
y = 2 * np.ones((5, 5), dtype=int)
check = x * y[:, :, None]
print(check)

[[[2 2 2]
  [2 2 2]
  [2 2 2]
  [2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]
  [2 2 2]
  [2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]
  [2 2 2]
  [2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]
  [2 2 2]
  [2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]
  [2 2 2]
  [2 2 2]
  [2 2 2]]]


72. How to swap two rows of an array?

In [180]:
x = np.arange(9).reshape(3, 3)
x[[0, 1]] = x[[1, 0]]
print(x)

[[3 4 5]
 [0 1 2]
 [6 7 8]]


73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles

In [182]:
x = np.random.randint(0, 10, (10, 3))
q = np.roll(x.repeat(2, axis=1), -1, axis=1)
q = q.reshape(len(q)*3, 2)
q = np.sort(q, axis=1)
fin = q.view(dtype=[('p0', q.dtype), ('p1', q.dtype)])
fin = np.unique(fin)
print(fin)


[(0, 9) (1, 4) (1, 5) (1, 9) (2, 4) (2, 6) (2, 8) (2, 9) (3, 5) (3, 9)
 (4, 5) (4, 6) (4, 7) (4, 9) (5, 5) (5, 7) (5, 8) (5, 9) (6, 8) (6, 9)
 (9, 9)]


74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?

In [183]:
c = np.bincount([1, 1, 2, 4, 5])
a = np.repeat(np.arange(len(c)), c)
print(a)

[1 1 2 4 5]


75. How to compute averages using a sliding window over an array?

In [186]:
def move(x, n = 3):
    q = np.cumsum(a, dtype=float)
    q[n:] = q[n:] - q[:-n]
    return q[n - 1:] / n
p = np.arange(20)
print(move(p, n = 3))

[1.33333333 2.33333333 3.66666667]


76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) 

In [190]:
from numpy.lib import stride_tricks

def shake(x, y):
    shape = (x.size - y + 1, y)
    strides = (x.itemsize, x.itemsize)
    return stride_tricks.as_strided(x, shape=shape, strides=strides)
p = shake(np.arange(10), 3)
print(p)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


77. How to negate a boolean, or to change the sign of a float inplace?

In [193]:
x = np.random.randint(0, 2, 10)
check = np.logical_not(x, out=x)
print(check)

x = np.random.uniform(-1.0, 1.0, 10)
check = np.negative(x, out=x)
print(check)

[1 1 0 1 1 1 1 0 1 0]
[-0.14260127  0.67837399 -0.16581615 -0.36918877 -0.95020488 -0.77772803
  0.5602042   0.72430678  0.75270658  0.06653833]


78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

In [196]:
def metr(p0, p1, p):
    rast = p1 - p0
    kek = (rast**2).sum(axis=1)
    check = -((p0[:, 0] - p[..., 0]) * rast[:, 0] + (p0[:, 1] - p[..., 1]) * rast[:, 1]) / kek
    check = check.reshape(len(check), 1)
    dist = p0 + check * rast - p
    return np.sqrt((dist**2).sum(axis=1))
p0 = np.random.uniform(-10, 10, (10, 2))
p1 = np.random.uniform(-10, 10, (10, 2))
p = np.random.uniform(-10, 10, (10, 2))
print(metr(p0, p1, p))

[ 2.04739134  0.67821856  1.49059882  1.57253251  6.68786163 15.57098422
  5.32964526  0.32894089  1.05818083  5.85774469]


79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?

In [199]:
p0 = np.random.uniform(-10, 10, (10, 2))
p1 = np.random.uniform(-10, 10, (10, 2))
p = np.random.uniform(-10, 10, (10, 2))
print(np.array([metr(p0, p1, x) for x in p]))

[[13.07461457  0.25987521  2.79843799 12.62869217  3.3567584   8.56657368
   4.06484228  9.28879449 12.79555988  5.67763039]
 [ 6.52308506 18.40255712 17.77196585  7.2366253  14.43824538  3.48703483
   4.37756587  5.52305231  6.04847067 11.09894442]
 [ 3.31021299 14.49520172 18.01589228  4.27729021 10.04014407  3.08098679
   2.37746627  1.19674197  8.23293304 14.53423847]
 [ 4.75702494 17.5396825  12.42529366  5.15917924 14.26491028 11.09319464
   8.80460399 12.94937467  0.74362184  3.61236575]
 [ 4.72634863 17.64607211 11.81469723  5.08051518 14.47389435 12.28484929
   9.65044051 14.12879838  1.61662402  2.59674896]
 [ 7.62304608 18.9216404  21.18029488  8.5369628  14.51416555  1.41046201
   1.50404966  0.73894059 10.39291848 15.89567153]
 [13.08790443  0.96354278  0.13506018 12.39975811  4.57572822  2.53800008
   8.44819511  3.31117782  8.50993075  0.64736027]
 [ 7.69761652 19.25745433 20.12907696  8.51965952 15.04437293  0.8817359
   3.21372149  3.016269    8.817431   14.02750112]
 

80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)

81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

In [250]:
z = np.arange(1, 15, dtype=np.uint32)
r = stride_tricks.as_strided(z, (11, 4), (4, 4))
print(r)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


82. Compute a matrix rank

In [252]:
x = np.random.uniform(0, 1, (10, 10))
y, z, q = np.linalg.svd(x)
r = np.sum(z > 1e-10)
print(r)

10


83. How to find the most frequent value in an array?

In [254]:
x = np.random.randint(0, 10, 20)
y = np.bincount(x).argmax()
print(y)

4


84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix 

In [256]:
x = np.random.randint(0, 5, (10, 10))
p = 3
y = 1 + (x.shape[0] - 3)
z = 1 + (x.shape[1] - 3)
check = stride_tricks.as_strided(x, shape=(y, z, n, n), strides=x.strides + x.strides)
print(check)


[[[[                   0                    0                    2
                       4                    0]
   [                   3                    2                    0
                       1                    2]
   [                   1                    1                    2
                       1                    4]
   [                   3                    4                    4
                       2                    4]
   [                   3                    2                    3
                       4                    3]]

  [[                   0                    2                    4
                       0                    0]
   [                   2                    0                    1
                       2                    0]
   [                   1                    2                    1
                       4                    4]
   [                   4                    4                    2
                   

85. Create a 2D array subclass such that Z[i,j] == Z[j,i]

In [306]:
class Sym(np.ndarray):
    def __set__(m, i, v):
        a, b = i
        super(Sym, m).__set__((a, b), v)
        super(Sym, m).__set__((b, a), v)

def switch(x):
    return np.asarray(x + x.T - np.diag(x.diagonal())).view(Sym)

k = switch(np.random.randint(0, 5, (5, 5)))
k[2, 3] = 24
print(k)

[[ 0  5  2  1  2]
 [ 5  2  4  7  6]
 [ 2  4  2 24  0]
 [ 1  7  4  1  5]
 [ 2  6  0  5  0]]


86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))

In [307]:
n, p = 5, 10
z = np.ones((p, n, n), dtype=int)
y = np.ones((p, n, 1), dtype=int)
x = np.tensordot(z, y, axes=[[0, 2], [0, 1]])
print(x)

[[50]
 [50]
 [50]
 [50]
 [50]]


87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

In [308]:
x = np.ones((16, 16), dtype=int)
check = np.add.reduceat(np.add.reduceat(x, np.arange(0, x.shape[0], 4), axis=0),
                                        np.arange(0, x.shape[1], 4), axis=1)
print(check)

[[16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]]


88. How to implement the Game of Life using numpy arrays? 

In [309]:
def iterate(Z):
    N = (Z[0:-2, 0:-2] + Z[0:-2, 1:-1] + Z[0:-2, 2:] +
         Z[1:-1, 0:-2] + Z[1:-1, 2:] + Z[2:, 0:-2] + 
         Z[2:, 1:-1] + Z[2:, 2:])

    birth = (N == 3) & (Z[1:-1, 1:-1] == 0)
    survive = ((N == 2) | (N == 3)) & (Z[1:-1, 1:-1] == 1)
    Z[...] = 0
    Z[1:-1, 1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0, 2, (50, 50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 1 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 1 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 1 1 1 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0

89. How to get the n largest values of an array

In [310]:
x = np.arange(100)
np.random.shuffle(x)
n = 5
y = x[np.argsort(x)[-n:]]
print(y)

[95 96 97 98 99]


90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)

In [311]:
def tree(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (tree(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


91. How to create a record array from a regular array?

In [312]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods

In [313]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

395 ms ± 2.58 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
66.1 ms ± 3.71 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
65.8 ms ± 657 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

In [315]:
A = np.random.randint(0, 5, (8, 3))
B = np.random.randint(0, 5, (2, 2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3, 1)).all(1))[0]
print(rows)

[0 1 2 3 4 6]


94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

In [318]:
Z = np.random.randint(0,5,(10,3))
print(Z)

[[3 2 2]
 [4 2 0]
 [0 4 1]
 [3 0 3]
 [4 3 3]
 [3 0 1]
 [1 1 0]
 [2 3 4]
 [1 4 2]
 [0 4 3]]


95. Convert a vector of ints into a matrix binary representation

In [319]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


96. Given a two dimensional array, how to extract unique rows?

In [320]:
Z = np.random.randint(0, 2, (6, 3))
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 1 0]
 [1 1 1]]



97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

In [322]:
A = np.random.uniform(0, 1, 5)
B = np.random.uniform(0, 1, 5)

np.einsum('i->', A)
np.einsum('i,i->i', A, B)
np.einsum('i,i', A, B)
np.einsum('i,j->ij', A, B)

array([[0.08147448, 0.0991071 , 0.07127163, 0.16554427, 0.00840854],
       [0.01207311, 0.01468596, 0.01056123, 0.02453081, 0.001246  ],
       [0.12043341, 0.14649749, 0.10535183, 0.24470315, 0.01242928],
       [0.30157754, 0.36684466, 0.26381174, 0.61276164, 0.0311242 ],
       [0.02823846, 0.0343498 , 0.02470223, 0.05737644, 0.00291434]])

98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples

In [323]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)
r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x)
y_int = np.interp(r_int, r, y)

99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.

In [324]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). 

In [325]:
X = np.random.randn(100)
N = 1000
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.31218603  0.05556338]
